spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  groovy:
    template:
      check-template-location: false
hydra:
  numThreadsForSaleLimit: 8

---
spring:
  profiles: default
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/hydra-pos-state

hydra:
  sns:
    topicArn: 'arn:aws:sns:us-east-1:hydra-send-to-store-or-pos-dev'
  s3:
    sendToStoreBucket: 'hydra-send-to-store-buffer-dev'

accesskey:
  url: "https://teste.com"
  valueReturn: "x-api-key"
  apiKey: "teste"
